name: "Incus Agent"
version: "1.0.4"
slug: "incus_agent"
description: "Runs incus-agent to provide metrics to an Incus host"
arch:
  - aarch64
  - amd64
init: false
startup: "system"
boot: "auto"

# Zásadní část: Udělení oprávnění
host_network: true # Umožní agentovi vidět síť hostitele
host_pid: true # Umožní agentovi vidět procesy hostitele
hassio_api: false
hassio_role: default
protection_mode: false

# Volitelné, ale může být potřeba pro plný přístup
# Pokud by agent stále neměl přístup k některým metrikám,
# odkomentujte následující řádek.
# protection_mode: false

# Prozatím nebudeme definovat žádné uživatelské volby
options: {}
schema: {}
privileged:
  - SYS_ADMIN
apparmor: false
